/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RecebimentoRouteImport } from './routes/recebimento'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NotasFiscaisRouteImport } from './routes/notas-fiscais'
import { Route as InternoRouteImport } from './routes/interno'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DocasRouteImport } from './routes/docas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ColetaRouteImport } from './routes/coleta'
import { Route as CargasRouteImport } from './routes/cargas'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrosIndexRouteImport } from './routes/cadastros.index'
import { Route as CadastrosMotoristasRouteImport } from './routes/cadastros.motoristas'
import { Route as CadastrosFiliaisRouteImport } from './routes/cadastros.filiais'
import { Route as CadastrosConferentesRouteImport } from './routes/cadastros.conferentes'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoRoute = RecebimentoRouteImport.update({
  id: '/recebimento',
  path: '/recebimento',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasFiscaisRoute = NotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const InternoRoute = InternoRouteImport.update({
  id: '/interno',
  path: '/interno',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DocasRoute = DocasRouteImport.update({
  id: '/docas',
  path: '/docas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ColetaRoute = ColetaRouteImport.update({
  id: '/coleta',
  path: '/coleta',
  getParentRoute: () => rootRouteImport,
} as any)
const CargasRoute = CargasRouteImport.update({
  id: '/cargas',
  path: '/cargas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosIndexRoute = CadastrosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CadastrosRoute,
} as any)
const CadastrosMotoristasRoute = CadastrosMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => CadastrosRoute,
} as any)
const CadastrosFiliaisRoute = CadastrosFiliaisRouteImport.update({
  id: '/filiais',
  path: '/filiais',
  getParentRoute: () => CadastrosRoute,
} as any)
const CadastrosConferentesRoute = CadastrosConferentesRouteImport.update({
  id: '/conferentes',
  path: '/conferentes',
  getParentRoute: () => CadastrosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRouteWithChildren
  '/cargas': typeof CargasRoute
  '/coleta': typeof ColetaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/docas': typeof DocasRoute
  '/historico': typeof HistoricoRoute
  '/interno': typeof InternoRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
  '/portal': typeof PortalRoute
  '/recebimento': typeof RecebimentoRoute
  '/usuarios': typeof UsuariosRoute
  '/cadastros/conferentes': typeof CadastrosConferentesRoute
  '/cadastros/filiais': typeof CadastrosFiliaisRoute
  '/cadastros/motoristas': typeof CadastrosMotoristasRoute
  '/cadastros/': typeof CadastrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cargas': typeof CargasRoute
  '/coleta': typeof ColetaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/docas': typeof DocasRoute
  '/historico': typeof HistoricoRoute
  '/interno': typeof InternoRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
  '/portal': typeof PortalRoute
  '/recebimento': typeof RecebimentoRoute
  '/usuarios': typeof UsuariosRoute
  '/cadastros/conferentes': typeof CadastrosConferentesRoute
  '/cadastros/filiais': typeof CadastrosFiliaisRoute
  '/cadastros/motoristas': typeof CadastrosMotoristasRoute
  '/cadastros': typeof CadastrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRouteWithChildren
  '/cargas': typeof CargasRoute
  '/coleta': typeof ColetaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/docas': typeof DocasRoute
  '/historico': typeof HistoricoRoute
  '/interno': typeof InternoRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
  '/portal': typeof PortalRoute
  '/recebimento': typeof RecebimentoRoute
  '/usuarios': typeof UsuariosRoute
  '/cadastros/conferentes': typeof CadastrosConferentesRoute
  '/cadastros/filiais': typeof CadastrosFiliaisRoute
  '/cadastros/motoristas': typeof CadastrosMotoristasRoute
  '/cadastros/': typeof CadastrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/cargas'
    | '/coleta'
    | '/configuracoes'
    | '/docas'
    | '/historico'
    | '/interno'
    | '/notas-fiscais'
    | '/portal'
    | '/recebimento'
    | '/usuarios'
    | '/cadastros/conferentes'
    | '/cadastros/filiais'
    | '/cadastros/motoristas'
    | '/cadastros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cargas'
    | '/coleta'
    | '/configuracoes'
    | '/docas'
    | '/historico'
    | '/interno'
    | '/notas-fiscais'
    | '/portal'
    | '/recebimento'
    | '/usuarios'
    | '/cadastros/conferentes'
    | '/cadastros/filiais'
    | '/cadastros/motoristas'
    | '/cadastros'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/cargas'
    | '/coleta'
    | '/configuracoes'
    | '/docas'
    | '/historico'
    | '/interno'
    | '/notas-fiscais'
    | '/portal'
    | '/recebimento'
    | '/usuarios'
    | '/cadastros/conferentes'
    | '/cadastros/filiais'
    | '/cadastros/motoristas'
    | '/cadastros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRouteWithChildren
  CargasRoute: typeof CargasRoute
  ColetaRoute: typeof ColetaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocasRoute: typeof DocasRoute
  HistoricoRoute: typeof HistoricoRoute
  InternoRoute: typeof InternoRoute
  NotasFiscaisRoute: typeof NotasFiscaisRoute
  PortalRoute: typeof PortalRoute
  RecebimentoRoute: typeof RecebimentoRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento': {
      id: '/recebimento'
      path: '/recebimento'
      fullPath: '/recebimento'
      preLoaderRoute: typeof RecebimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas-fiscais': {
      id: '/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof NotasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interno': {
      id: '/interno'
      path: '/interno'
      fullPath: '/interno'
      preLoaderRoute: typeof InternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docas': {
      id: '/docas'
      path: '/docas'
      fullPath: '/docas'
      preLoaderRoute: typeof DocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleta': {
      id: '/coleta'
      path: '/coleta'
      fullPath: '/coleta'
      preLoaderRoute: typeof ColetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargas': {
      id: '/cargas'
      path: '/cargas'
      fullPath: '/cargas'
      preLoaderRoute: typeof CargasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/': {
      id: '/cadastros/'
      path: '/'
      fullPath: '/cadastros/'
      preLoaderRoute: typeof CadastrosIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/motoristas': {
      id: '/cadastros/motoristas'
      path: '/motoristas'
      fullPath: '/cadastros/motoristas'
      preLoaderRoute: typeof CadastrosMotoristasRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/filiais': {
      id: '/cadastros/filiais'
      path: '/filiais'
      fullPath: '/cadastros/filiais'
      preLoaderRoute: typeof CadastrosFiliaisRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/conferentes': {
      id: '/cadastros/conferentes'
      path: '/conferentes'
      fullPath: '/cadastros/conferentes'
      preLoaderRoute: typeof CadastrosConferentesRouteImport
      parentRoute: typeof CadastrosRoute
    }
  }
}

interface CadastrosRouteChildren {
  CadastrosConferentesRoute: typeof CadastrosConferentesRoute
  CadastrosFiliaisRoute: typeof CadastrosFiliaisRoute
  CadastrosMotoristasRoute: typeof CadastrosMotoristasRoute
  CadastrosIndexRoute: typeof CadastrosIndexRoute
}

const CadastrosRouteChildren: CadastrosRouteChildren = {
  CadastrosConferentesRoute: CadastrosConferentesRoute,
  CadastrosFiliaisRoute: CadastrosFiliaisRoute,
  CadastrosMotoristasRoute: CadastrosMotoristasRoute,
  CadastrosIndexRoute: CadastrosIndexRoute,
}

const CadastrosRouteWithChildren = CadastrosRoute._addFileChildren(
  CadastrosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRouteWithChildren,
  CargasRoute: CargasRoute,
  ColetaRoute: ColetaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocasRoute: DocasRoute,
  HistoricoRoute: HistoricoRoute,
  InternoRoute: InternoRoute,
  NotasFiscaisRoute: NotasFiscaisRoute,
  PortalRoute: PortalRoute,
  RecebimentoRoute: RecebimentoRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
